

services:
  - type: web
    name: heatpredService
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn heartPredApp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heartPredApp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4