# Generated by Django 5.0.1 on 2024-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HDDiagosticFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Sex', models.IntegerField()),
                ('chest_pain_type', models.IntegerField()),
                ('BP', models.IntegerField()),
                ('Cholesterol', models.IntegerField()),
                ('FBS_over_120', models.IntegerField()),
                ('EKG_results', models.IntegerField()),
                ('Max_HR', models.IntegerField()),
                ('Exercise_angina', models.IntegerField()),
                ('ST_depression', models.IntegerField()),
                ('Slope_of_ST', models.IntegerField()),
                ('Number_of_vessels_fluro', models.IntegerField()),
                ('Thallium', models.IntegerField()),
            ],
        ),
    ]
